from pathlib import Path
import sys


SCRAPER_DIR = Path(__file__).resolve().parents[1]
if str(SCRAPER_DIR) not in sys.path:
    sys.path.insert(0, str(SCRAPER_DIR))

from storage.database import connect, get_db_path, init_db  # noqa: E402
from storage.repositories import create_product, create_shop, create_tracked_product, list_products, list_shops  # noqa: E402


FAKE_SHOP_URL = "http://localhost:8080/index.html?price=39.99&stock=in"


def seed_shops() -> None:
    shops = [
        {
            "name": "Fake Shop",
            "url": "http://localhost:8080",
            "scraper_key": "fake_shop",
            "country": "local",
            "type": "fake",
            "priority": "high",
            "difficulty": "easy",
            "integration_status": "functional",
            "notes": "Boutique locale de test.",
            "active": True,
            "trusted": True,
        },
        {
            "name": "Otakuland-Manga Passion",
            "url": "https://otakuland-mangapassion.com",
            "scraper_key": "otakuland",
            "country": "FR/EU",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "medium",
            "integration_status": "functional",
            "notes": "Fonctionnel V1 uniquement pour pages produit simples sans options obligatoires. Source FR/EU secondaire : verifier frais de port vers Belgique avant de considerer un deal comme pertinent.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Outpost Brussels",
            "url": "https://outpostbrussels.be",
            "scraper_key": "outpost_brussels",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "high",
            "difficulty": "medium",
            "integration_status": "functional",
            "notes": "Fonctionnel uniquement pour OutpostBrusselsScraper V1 : pages produit Shopify simples, parsing JSON-LD prioritaire, pas de crawl catalogue.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "SOD Games",
            "url": "https://www.sodgames.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "high",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique belge candidate BE-first avec section Pokemon TCG. A analyser avant scraper.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "TCG PokAlex",
            "url": "https://www.tcgpokalex.com",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "high",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique belge TCG basee en Belgique. Produits sealed Pokemon a analyser.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Strategy Games",
            "url": "https://strategygames.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "high",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique belge TCG avec produits Pokemon sealed et frais de livraison Belgique a verifier.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Dreamland BE",
            "url": "https://www.dreamland.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "retailer",
            "priority": "high",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Retailer belge pertinent pour cartes Pokemon et produits sealed.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Kuro Star",
            "url": "https://kurostar.com",
            "scraper_key": "not_configured",
            "country": "FR/EU",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Source FR/EU utile mais secondaire pour CardSnip BE-first. Verifier frais de port vers Belgique avant priorite.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Pikastore",
            "url": "https://www.pikastore.fr",
            "scraper_key": "not_configured",
            "country": "FR/EU",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Source FR/EU utile mais secondaire pour CardSnip BE-first. Verifier frais de port vers Belgique avant priorite.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "UltraJeux",
            "url": "https://www.ultrajeux.com",
            "scraper_key": "not_configured",
            "country": "FR",
            "type": "tcg_specialist",
            "priority": "low",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Source FR utile mais secondaire pour CardSnip BE-first. Verifier frais de port vers Belgique avant priorite.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Fnac BE",
            "url": "https://www.fr.fnac.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Retailer belge/francophone. Attention disponibilite reelle, vendeurs tiers eventuels et frais de port.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Fnac FR",
            "url": "https://www.fnac.com",
            "scraper_key": "not_configured",
            "country": "FR",
            "type": "retailer",
            "priority": "low",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Source FR/EU utile mais secondaire pour CardSnip BE-first. Verifier frais de port vers Belgique avant priorite.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Cultura",
            "url": "https://www.cultura.com",
            "scraper_key": "not_configured",
            "country": "FR",
            "type": "retailer",
            "priority": "low",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Source FR/EU utile mais secondaire pour CardSnip BE-first. Verifier frais de port vers Belgique avant priorite.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Coolblue",
            "url": "https://www.coolblue.be",
            "scraper_key": "not_configured",
            "country": "BE/NL",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Bol.com",
            "url": "https://www.bol.com/be/fr",
            "scraper_key": "not_configured",
            "country": "BE/NL",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock, vendeurs tiers et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "MediaMarkt BE",
            "url": "https://www.mediamarkt.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Carrefour BE",
            "url": "https://www.carrefour.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Trafic",
            "url": "https://www.trafic.com",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "retailer",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Le P'tit Poucet",
            "url": None,
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. URL a confirmer. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Cards Corner",
            "url": None,
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. URL a confirmer. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "PokemonStore.be",
            "url": "https://www.pokemonstore.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Collect Them All",
            "url": None,
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. URL a confirmer. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Pockinity",
            "url": None,
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. URL a confirmer. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Gamealot",
            "url": "https://www.gamealot.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Spelonk",
            "url": "https://www.spelonk.be",
            "scraper_key": "not_configured",
            "country": "BE/NL",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "CardWorld",
            "url": None,
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "tcg_specialist",
            "priority": "medium",
            "difficulty": "unknown",
            "integration_status": "to_analyze",
            "notes": "Boutique/source belge a verifier avant scraper. URL a confirmer. Confirmer produits Pokemon sealed, frais, stock et structure HTML.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "Amazon",
            "url": "https://www.amazon.fr",
            "scraper_key": "not_configured",
            "country": "EU",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "later",
            "notes": "Marketplace complexe avec vendeurs tiers, invitations, stock/prix variables et anti-bot possible. A garder plus tard, pas source BE-first.",
            "active": False,
            "trusted": False,
        },
        {
            "name": "Cardmarket",
            "url": "https://www.cardmarket.com",
            "scraper_key": "not_configured",
            "country": "EU",
            "type": "marketplace_reference",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "later",
            "notes": "A garder uniquement comme reference marche plus tard, pas comme source d'achat recommandee CardSnip.",
            "active": False,
            "trusted": True,
        },
        {
            "name": "eBay",
            "url": "https://www.ebay.fr",
            "scraper_key": "not_configured",
            "country": "global",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "disabled",
            "notes": "Non recommande comme source d'achat CardSnip : risques de faux produits, resealed, vendeurs douteux, frais caches ou fiabilite variable.",
            "active": False,
            "trusted": False,
        },
        {
            "name": "Vinted",
            "url": "https://www.vinted.be",
            "scraper_key": "not_configured",
            "country": "BE/EU",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "disabled",
            "notes": "Non recommande comme source d'achat CardSnip : risques de faux produits, resealed, vendeurs douteux, frais caches ou fiabilite variable.",
            "active": False,
            "trusted": False,
        },
        {
            "name": "Leboncoin",
            "url": "https://www.leboncoin.fr",
            "scraper_key": "not_configured",
            "country": "FR",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "disabled",
            "notes": "Non recommande comme source d'achat CardSnip : risques de faux produits, resealed, vendeurs douteux, frais caches ou fiabilite variable.",
            "active": False,
            "trusted": False,
        },
        {
            "name": "2ememain",
            "url": "https://www.2ememain.be",
            "scraper_key": "not_configured",
            "country": "BE",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "disabled",
            "notes": "Non recommande comme source d'achat CardSnip : risques de faux produits, resealed, vendeurs douteux, frais caches ou fiabilite variable.",
            "active": False,
            "trusted": False,
        },
        {
            "name": "Facebook Marketplace",
            "url": "https://www.facebook.com/marketplace",
            "scraper_key": "not_configured",
            "country": "global",
            "type": "marketplace",
            "priority": "later",
            "difficulty": "hard",
            "integration_status": "disabled",
            "notes": "Non recommande comme source d'achat CardSnip : risques de faux produits, resealed, vendeurs douteux, frais caches ou fiabilite variable.",
            "active": False,
            "trusted": False,
        },
    ]

    with connect() as connection:
        connection.execute(
            """
            update shops
            set name = 'Otakuland-Manga Passion'
            where name = 'Otakuland'
            """
        )
        existing_names = {shop["name"] for shop in list_shops(connection)}
        for shop in shops:
            if shop["name"] not in existing_names:
                create_shop(connection, shop)
            else:
                connection.execute(
                    """
                    update shops
                    set
                      url = :url,
                      scraper_key = :scraper_key,
                      country = :country,
                      type = :type,
                      priority = :priority,
                      difficulty = :difficulty,
                      integration_status = :integration_status,
                      notes = :notes,
                      active = :active,
                      trusted = :trusted
                    where name = :name
                    """,
                    {
                        **shop,
                        "active": int(bool(shop["active"])),
                        "trusted": int(bool(shop["trusted"])),
                    },
                )
        connection.commit()


def seed_demo_product() -> None:
    with connect() as connection:
        products = list_products(connection)
        if products:
            return

        product = create_product(
            connection,
            {
                "name": "Elite Trainer Box - Edition Demo",
                "category": "ETB",
                "language": "FR",
                "extension": "Demo",
                "image_url": None,
            },
        )
        fake_shop = next(shop for shop in list_shops(connection) if shop["name"] == "Fake Shop")
        create_tracked_product(
            connection,
            {
                "product_id": product["id"],
                "shop_id": fake_shop["id"],
                "source_url": FAKE_SHOP_URL,
                "target_price": 45.0,
                "active": True,
            },
        )


def main() -> None:
    init_db()
    seed_shops()
    seed_demo_product()
    print(f"Base SQLite initialisee: {get_db_path()}")
    print("Seed: boutiques mockees + produit demo fake shop.")


if __name__ == "__main__":
    main()
